module.exports = [
  "Administração",
  "Agente de Saúde",
  "Análises Clínicas",
  "Auxiliar Veterinário",
  "Barbeiro",
  "Cabeleireiro",
  "Contabilidade",
  "Cuidador de Idosos",
  "Designer Gráfico",
  "Enfermagem",
  "Farmácia",
  "Gastronomia",
  "Gestão e Logística",
  "Inglês",
  "Informática",
  "Marketing Digital",
  "Massoterapia",
  "Nutrição",
  "Odontologia",
  "Operador de Caixa",
  "Pedagogia",
  "Psicologia",
  "Recepcionista Hospitalar",
  "Recursos Humanos",
  "Robótica",
  "Segurança do Trabalho",
  "Socorrista"
]
