"use strict";

function createDefaultConversation() {
  return {
    step: "menu",
    path: "",
    course: "",
    goal: "",
    experience: "",
    payment: "",
    paymentTeaserShown: false,
    commercialStage: "discovery",
    priceShown: false,
    enrollmentIntent: false,
    objectiveCapturedAt: "",
    askToCloseCount: 0,
    lastQuestionKey: "",
    lastOfferSignature: "",
    currentFlow: "commercial",
    awaitingMainIntent: false,
    pendingStep: "",
    pendingStepSince: "",
    pendingStepContext: null,
    lastBotAction: "",
    lastOfferType: "",
    lastSuggestedCourses: [],
    preferredCategory: "",
    mentionedCategories: [],
    alreadySuggestedCourses: false,
    alreadyAnsweredPrice: false,
    lastCommercialResponseHash: "",
    repeatedResponseGuard: {
      sameHashCount: 0,
      lastRepeatedAt: "",
      lastIntent: ""
    },
    lastBotMessage: "",
    lastBotMessageHash: "",
    lastUserMessageHash: "",
    lastIntent: "",
    lastHandledIntent: "",
    lastIntentHandled: "",
    awaitingConfirmation: false,
    userGoal: "",
    userExperienceLevel: "",
    courseCatalogOffered: false,
    awaitingCourseChoice: false,
    awaitingCareerDiscovery: false,
    coursePresentationSent: false,
    selectedCourse: null,
    coursePresentationLevel: "none",
    selectedCategory: "",
    paymentPreference: "",
    paymentInterest: "",
    awaitingPriceDecision: false,
    awaitingEnrollmentInterest: false,
    awaitingEnrollmentConfirmation: false,
    awaitingEnrollmentData: false,
    financialFlowLocked: false,
    askedHowItWorks: false,
    askedDuration: false,
    askedMoreCourses: false,
    name: "",
    cpf: "",
    birthDate: "",
    email: "",
    gender: "",
    phone: "",
    cep: "",
    street: "",
    number: "",
    complement: "",
    neighborhood: "",
    city: "",
    state: "",
    deferredPaymentDay: "",
    dueDay: "",
    alunoId: null,
    contratoId: null,
    parcelaId: null,
    nossoNumero: "",
    internalLeadNotified: false,
    internalLeadNotifiedAt: "",
    internalLeadNotifyKey: "",
    lastUserText: "",
    lastAssistantText: "",
    lastStepWhenAnswered: "",
    updatedAt: "",
  };
}

module.exports = {
  createDefaultConversation,
};
